"""empty message

Revision ID: 0bfb9d077f43
Revises: 816c77b48793
Create Date: 2020-05-11 05:25:18.172075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfb9d077f43'
down_revision = '816c77b48793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('shows_Artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_Venue_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'Venue', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Artist', ['venue_id'], ['id'])
    op.drop_column('shows', 'Artist_id')
    op.drop_column('shows', 'Venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_Venue_id_fkey', 'shows', 'Artist', ['Venue_id'], ['id'])
    op.create_foreign_key('shows_Artist_id_fkey', 'shows', 'Venue', ['Artist_id'], ['id'])
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'artist_id')
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
