"""empty message

Revision ID: 32b506177c43
Revises: 59297ff6518d
Create Date: 2020-05-12 02:39:28.915848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b506177c43'
down_revision = '59297ff6518d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Venue.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
