"""empty message

Revision ID: 59297ff6518d
Revises: ed074312bfdd
Create Date: 2020-05-12 02:29:33.063736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59297ff6518d'
down_revision = 'ed074312bfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Venue.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
