"""empty message

Revision ID: 816c77b48793
Revises: b0eb01d7cacb
Create Date: 2020-05-11 02:25:13.588200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816c77b48793'
down_revision = 'b0eb01d7cacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
